"""empty message

Revision ID: 0f39fd3b057b
Revises: e7a4faa3d7b1
Create Date: 2020-11-07 23:49:58.761570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f39fd3b057b'
down_revision = 'e7a4faa3d7b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=True),
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('about', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('role_admin', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_role_admin_about'), ['about'], unique=True)
        batch_op.create_index(batch_op.f('ix_role_admin_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_role_admin_name'), ['name'], unique=True)

    op.create_table('role_employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=True),
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('about', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('role_employee', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_role_employee_about'), ['about'], unique=True)
        batch_op.create_index(batch_op.f('ix_role_employee_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_role_employee_name'), ['name'], unique=True)

    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_admin_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'role_admin', ['role_admin_id'], ['id'])
        batch_op.drop_column('role')

    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_employee_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'role_employee', ['role_employee_id'], ['id'])
        batch_op.drop_column('role')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_slug')
        batch_op.create_index(batch_op.f('ix_user_slug'), ['slug'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_slug'))
        batch_op.create_index('ix_user_slug', ['slug'], unique=True)

    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.VARCHAR(length=140), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('role_employee_id')

    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.VARCHAR(length=140), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('role_admin_id')

    with op.batch_alter_table('role_employee', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_role_employee_name'))
        batch_op.drop_index(batch_op.f('ix_role_employee_code'))
        batch_op.drop_index(batch_op.f('ix_role_employee_about'))

    op.drop_table('role_employee')
    with op.batch_alter_table('role_admin', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_role_admin_name'))
        batch_op.drop_index(batch_op.f('ix_role_admin_code'))
        batch_op.drop_index(batch_op.f('ix_role_admin_about'))

    op.drop_table('role_admin')
    # ### end Alembic commands ###
