"""empty message

Revision ID: 13677a0c9b2d
Revises: 0f39fd3b057b
Create Date: 2020-11-08 00:16:58.183130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13677a0c9b2d'
down_revision = '0f39fd3b057b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_slug')
        batch_op.create_index(batch_op.f('ix_user_slug'), ['slug'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_slug'))
        batch_op.create_index('ix_user_slug', ['slug'], unique=False)

    # ### end Alembic commands ###
