"""empty message

Revision ID: 14a3924e1f3f
Revises: e0d15291d0a4
Create Date: 2021-01-24 15:37:04.270114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14a3924e1f3f'
down_revision = 'e0d15291d0a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('call_in', schema=None) as batch_op:
        batch_op.drop_constraint('call_in_employee_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'employee', ['employee_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('call_in', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('call_in_employee_id_fkey', 'client_place', ['employee_id'], ['id'])

    # ### end Alembic commands ###
