"""empty message

Revision ID: 18385f544560
Revises: ea07d5386d18
Create Date: 2020-11-04 16:17:04.512060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18385f544560'
down_revision = 'ea07d5386d18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees_groups_client_places',
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('group_client_places_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['group_client_places_id'], ['group_client_places.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employees_groups_client_places')
    # ### end Alembic commands ###
