"""empty message

Revision ID: 1b51215e203b
Revises: 612e6e5540cf
Create Date: 2021-01-12 14:18:28.161649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b51215e203b'
down_revision = '612e6e5540cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.drop_index('ix_admin_slug')

    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_index('ix_client_slug')

    with op.batch_alter_table('client_place', schema=None) as batch_op:
        batch_op.drop_index('ix_client_place_slug')

    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_index('ix_company_slug')

    with op.batch_alter_table('corporation', schema=None) as batch_op:
        batch_op.drop_index('ix_corporation_slug')

    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_index('ix_employee_slug')

    with op.batch_alter_table('group_client_places', schema=None) as batch_op:
        batch_op.drop_index('ix_group_client_places_slug')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_slug')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('ix_user_slug', ['slug'], unique=True)

    with op.batch_alter_table('group_client_places', schema=None) as batch_op:
        batch_op.create_index('ix_group_client_places_slug', ['slug'], unique=True)

    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.create_index('ix_employee_slug', ['slug'], unique=True)

    with op.batch_alter_table('corporation', schema=None) as batch_op:
        batch_op.create_index('ix_corporation_slug', ['slug'], unique=True)

    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.create_index('ix_company_slug', ['slug'], unique=True)

    with op.batch_alter_table('client_place', schema=None) as batch_op:
        batch_op.create_index('ix_client_place_slug', ['slug'], unique=True)

    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.create_index('ix_client_slug', ['slug'], unique=True)

    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.create_index('ix_admin_slug', ['slug'], unique=True)

    # ### end Alembic commands ###
