"""empty message

Revision ID: 21c0605ae265
Revises: bfbc4b72cc00
Create Date: 2020-06-05 22:42:39.411528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21c0605ae265'
down_revision = 'bfbc4b72cc00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_client_place',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('client_place_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_place_id'], ['client_place.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_client_place')
    # ### end Alembic commands ###
