"""empty message

Revision ID: 2226bd2f894a
Revises: 5ab6dec0c7b3
Create Date: 2020-10-27 19:11:20.514201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2226bd2f894a'
down_revision = '5ab6dec0c7b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_person_id_fkey', type_='foreignkey')
        batch_op.drop_column('person_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('person_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('user_person_id_fkey', 'person', ['person_id'], ['id'])

    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
