"""empty message

Revision ID: 25397d1a9199
Revises: 4fc7ca443903
Create Date: 2020-11-06 22:28:32.034755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25397d1a9199'
down_revision = '4fc7ca443903'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.Integer(), nullable=True))
        batch_op.alter_column('corporation_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=140),
               nullable=False)
        batch_op.drop_constraint('admin_phone_number_telegram_key', type_='unique')
        batch_op.create_unique_constraint(None, ['phone'])
        batch_op.drop_column('phone_number_telegram')

    with op.batch_alter_table('corporation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creator_admin_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'admin', ['creator_admin_id'], ['id'])

    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.Integer(), nullable=True))
        batch_op.drop_constraint('employee_phone_number_telegram_key', type_='unique')
        batch_op.create_unique_constraint(None, ['phone'])
        batch_op.drop_column('phone_number_telegram')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('active')

    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number_telegram', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('employee_phone_number_telegram_key', ['phone_number_telegram'])
        batch_op.drop_column('phone')

    with op.batch_alter_table('corporation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('creator_admin_id')

    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number_telegram', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('admin_phone_number_telegram_key', ['phone_number_telegram'])
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=140),
               nullable=True)
        batch_op.alter_column('corporation_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('phone')
        batch_op.drop_column('active')

    # ### end Alembic commands ###
