"""empty message

Revision ID: 2659becb4042
Revises: 2226bd2f894a
Create Date: 2020-10-29 16:11:54.752367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2659becb4042'
down_revision = '2226bd2f894a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_constraint('client_person_id_fkey', type_='foreignkey')
        batch_op.drop_column('person_id')

    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_constraint('employee_person_id_fkey', type_='foreignkey')
        batch_op.drop_column('person_id')

    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('employee_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'employee', ['employee_id'], ['id'])
        batch_op.create_foreign_key(None, 'employee', ['client_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('employee_id')
        batch_op.drop_column('client_id')

    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('person_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('employee_person_id_fkey', 'person', ['person_id'], ['id'])

    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('person_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('client_person_id_fkey', 'person', ['person_id'], ['id'])

    # ### end Alembic commands ###
