"""empty message

Revision ID: 2c6a69f33c0b
Revises: 50d12a7f4b40
Create Date: 2021-02-26 20:12:45.650203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c6a69f33c0b'
down_revision = '50d12a7f4b40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('call_in', schema=None) as batch_op:
        batch_op.drop_column('creator_user_id')

    with op.batch_alter_table('call_out', schema=None) as batch_op:
        batch_op.drop_column('creator_user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('call_out', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creator_user_id', sa.INTEGER(), autoincrement=False, nullable=True))

    with op.batch_alter_table('call_in', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creator_user_id', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
