"""empty message

Revision ID: 2dd6c77dc2e4
Revises: f3a0ac8dd09c
Create Date: 2020-06-02 15:48:02.492806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dd6c77dc2e4'
down_revision = 'f3a0ac8dd09c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about', sa.String(length=140), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about', sa.String(length=140), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('about')

    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_column('about')

    # ### end Alembic commands ###
