"""empty message

Revision ID: 2fabe2b4dfcb
Revises: 1b51215e203b
Create Date: 2021-01-12 15:16:54.447767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fabe2b4dfcb'
down_revision = '1b51215e203b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_slug'), ['slug'], unique=True)

    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_slug'), ['slug'], unique=True)

    with op.batch_alter_table('client_place', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_place_slug'), ['slug'], unique=True)

    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_slug'), ['slug'], unique=True)

    with op.batch_alter_table('corporation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_corporation_slug'), ['slug'], unique=True)

    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employee_slug'), ['slug'], unique=True)

    with op.batch_alter_table('group_client_places', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_group_client_places_slug'), ['slug'], unique=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_slug'), ['slug'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_slug'))

    with op.batch_alter_table('group_client_places', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_group_client_places_slug'))

    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employee_slug'))

    with op.batch_alter_table('corporation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_corporation_slug'))

    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_slug'))

    with op.batch_alter_table('client_place', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_place_slug'))

    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_slug'))

    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_slug'))

    # ### end Alembic commands ###
