"""empty message

Revision ID: 3fd7ead04af7
Revises: 498e430450c7
Create Date: 2020-11-05 23:33:21.892737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fd7ead04af7'
down_revision = '498e430450c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('corporation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creator_admin_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'admin', ['creator_admin_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('corporation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('creator_admin_id')

    # ### end Alembic commands ###
