"""empty message

Revision ID: 498e430450c7
Revises: 6352b73b49b5
Create Date: 2020-11-05 23:31:16.051970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '498e430450c7'
down_revision = '6352b73b49b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('corporation_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'corporation', ['corporation_id'], ['id'])

    with op.batch_alter_table('corporation', schema=None) as batch_op:
        batch_op.drop_constraint('corporation_creator_admin_id_fkey', type_='foreignkey')
        batch_op.drop_column('creator_admin_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('corporation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creator_admin_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('corporation_creator_admin_id_fkey', 'admin', ['creator_admin_id'], ['id'])

    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('corporation_id')

    # ### end Alembic commands ###
