"""empty message

Revision ID: 4fc7ca443903
Revises: ca3e8588e1cd
Create Date: 2020-11-06 14:25:01.049357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fc7ca443903'
down_revision = 'ca3e8588e1cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees_to_groups_client_places',
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('group_client_places_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['group_client_places_id'], ['group_client_places.id'], )
    )
    op.create_table('employees_to_client_places',
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('client_place_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_place_id'], ['client_place.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employees_to_client_places')
    op.drop_table('employees_to_groups_client_places')
    # ### end Alembic commands ###
