"""empty message

Revision ID: 50d12a7f4b40
Revises: 887a4d9110ae
Create Date: 2021-02-25 23:17:33.925241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50d12a7f4b40'
down_revision = '887a4d9110ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_place', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug_link_cd', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_place', schema=None) as batch_op:
        batch_op.drop_column('slug_link_cd')

    # ### end Alembic commands ###
