"""empty message

Revision ID: 5ab6dec0c7b3
Revises: d385934a5825
Create Date: 2020-10-27 18:03:51.304392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ab6dec0c7b3'
down_revision = 'd385934a5825'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('phone_number_telegram', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_employee_email'), ['email'], unique=True)
        batch_op.create_unique_constraint(None, ['phone_number_telegram'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_index(batch_op.f('ix_employee_email'))
        batch_op.drop_column('phone_number_telegram')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
