"""empty message

Revision ID: 5b3c2af53037
Revises: 2fabe2b4dfcb
Create Date: 2021-01-24 12:36:31.592386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b3c2af53037'
down_revision = '2fabe2b4dfcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('type_call_in',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=True),
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('about', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('type_call_in', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_type_call_in_about'), ['about'], unique=True)
        batch_op.create_index(batch_op.f('ix_type_call_in_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_type_call_in_name'), ['name'], unique=True)

    op.create_table('type_call_out',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=True),
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('about', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('type_call_out', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_type_call_out_about'), ['about'], unique=True)
        batch_op.create_index(batch_op.f('ix_type_call_out_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_type_call_out_name'), ['name'], unique=True)

    op.create_table('call_out',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('creator_user_id', sa.Integer(), nullable=True),
    sa.Column('slug', sa.String(length=128), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=True),
    sa.Column('corporation_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('group_client_places_id', sa.Integer(), nullable=True),
    sa.Column('client_place_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('type_call_out_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['client_place_id'], ['client_place.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['corporation_id'], ['corporation.id'], ),
    sa.ForeignKeyConstraint(['group_client_places_id'], ['group_client_places.id'], ),
    sa.ForeignKeyConstraint(['type_call_out_id'], ['type_call_out.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('call_out', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_call_out_slug'), ['slug'], unique=True)

    op.create_table('call_in',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('creator_user_id', sa.Integer(), nullable=True),
    sa.Column('slug', sa.String(length=128), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=True),
    sa.Column('call_out_id', sa.Integer(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('type_call_in_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['call_out_id'], ['call_out.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['client_place.id'], ),
    sa.ForeignKeyConstraint(['type_call_in_id'], ['type_call_in.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('call_in', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_call_in_slug'), ['slug'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('call_in', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_call_in_slug'))

    op.drop_table('call_in')
    with op.batch_alter_table('call_out', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_call_out_slug'))

    op.drop_table('call_out')
    with op.batch_alter_table('type_call_out', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_type_call_out_name'))
        batch_op.drop_index(batch_op.f('ix_type_call_out_code'))
        batch_op.drop_index(batch_op.f('ix_type_call_out_about'))

    op.drop_table('type_call_out')
    with op.batch_alter_table('type_call_in', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_type_call_in_name'))
        batch_op.drop_index(batch_op.f('ix_type_call_in_code'))
        batch_op.drop_index(batch_op.f('ix_type_call_in_about'))

    op.drop_table('type_call_in')
    # ### end Alembic commands ###
