"""empty message

Revision ID: 5ccf0d6731f9
Revises: 21c0605ae265
Create Date: 2020-06-14 00:02:17.315484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ccf0d6731f9'
down_revision = '21c0605ae265'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_client_places',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('slug', sa.String(length=128), nullable=True),
    sa.Column('slug_link', sa.String(length=128), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('group_client_places', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_group_client_places_name_group_client_places'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_client_places_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_group_client_places_slug_link'), ['slug_link'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group_client_places', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_group_client_places_slug_link'))
        batch_op.drop_index(batch_op.f('ix_group_client_places_slug'))
        batch_op.drop_index(batch_op.f('ix_group_client_places_name_group_client_places'))

    op.drop_table('group_client_places')
    # ### end Alembic commands ###
