"""empty message

Revision ID: 6352b73b49b5
Revises: 
Create Date: 2020-11-05 23:28:13.567197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6352b73b49b5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('about', sa.String(length=140), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('slug', sa.String(length=128), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=140), nullable=True),
    sa.Column('about', sa.String(length=140), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone_number_telegram', sa.Integer(), nullable=True),
    sa.Column('slug', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number_telegram')
    )
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_admin_slug'), ['slug'], unique=True)

    op.create_table('corporation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('about', sa.String(length=140), nullable=True),
    sa.Column('slug', sa.String(length=128), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('creator_admin_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator_admin_id'], ['admin.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('corporation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_corporation_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_corporation_slug'), ['slug'], unique=True)

    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('about', sa.String(length=140), nullable=True),
    sa.Column('slug', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('corporation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['corporation_id'], ['corporation.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_slug'), ['slug'], unique=True)

    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('about', sa.String(length=140), nullable=True),
    sa.Column('slug', sa.String(length=128), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('corporation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['corporation_id'], ['corporation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_company_slug'), ['slug'], unique=True)

    op.create_table('employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('role', sa.String(length=140), nullable=True),
    sa.Column('about', sa.String(length=140), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone_number_telegram', sa.Integer(), nullable=True),
    sa.Column('slug', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('corporation_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['corporation_id'], ['corporation.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number_telegram')
    )
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employee_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_employee_first_name'), ['first_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_employee_last_name'), ['last_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_employee_slug'), ['slug'], unique=True)

    op.create_table('group_client_places',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('about', sa.String(length=140), nullable=True),
    sa.Column('slug', sa.String(length=128), nullable=True),
    sa.Column('slug_link', sa.String(length=128), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('group_client_places', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_group_client_places_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_client_places_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_group_client_places_slug_link'), ['slug_link'], unique=True)

    op.create_table('client_place',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('slug', sa.String(length=128), nullable=True),
    sa.Column('slug_link', sa.String(length=128), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('group_client_places_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['group_client_places_id'], ['group_client_places.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('client_place', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_place_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_place_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_client_place_slug_link'), ['slug_link'], unique=True)

    op.create_table('employee_to_group_client_places',
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('group_client_places_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['group_client_places_id'], ['group_client_places.id'], )
    )
    op.create_table('employee_to_client_place',
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('client_place_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_place_id'], ['client_place.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee_to_client_place')
    op.drop_table('employee_to_group_client_places')
    with op.batch_alter_table('client_place', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_place_slug_link'))
        batch_op.drop_index(batch_op.f('ix_client_place_slug'))
        batch_op.drop_index(batch_op.f('ix_client_place_name'))

    op.drop_table('client_place')
    with op.batch_alter_table('group_client_places', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_group_client_places_slug_link'))
        batch_op.drop_index(batch_op.f('ix_group_client_places_slug'))
        batch_op.drop_index(batch_op.f('ix_group_client_places_name'))

    op.drop_table('group_client_places')
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employee_slug'))
        batch_op.drop_index(batch_op.f('ix_employee_last_name'))
        batch_op.drop_index(batch_op.f('ix_employee_first_name'))
        batch_op.drop_index(batch_op.f('ix_employee_email'))

    op.drop_table('employee')
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_slug'))
        batch_op.drop_index(batch_op.f('ix_company_name'))

    op.drop_table('company')
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_slug'))

    op.drop_table('client')
    with op.batch_alter_table('corporation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_corporation_slug'))
        batch_op.drop_index(batch_op.f('ix_corporation_name'))

    op.drop_table('corporation')
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_slug'))
        batch_op.drop_index(batch_op.f('ix_admin_email'))

    op.drop_table('admin')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_slug'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    # ### end Alembic commands ###
