"""empty message

Revision ID: 6b70331c4f51
Revises: c7692d0835e5
Create Date: 2020-06-15 01:14:26.710412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b70331c4f51'
down_revision = 'c7692d0835e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group_client_places', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_group_client_places_name'), ['name'], unique=False)
        batch_op.drop_index('ix_group_client_places_name_group_client_places')
        batch_op.drop_column('name_group_client_places')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group_client_places', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name_group_client_places', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
        batch_op.create_index('ix_group_client_places_name_group_client_places', ['name_group_client_places'], unique=False)
        batch_op.drop_index(batch_op.f('ix_group_client_places_name'))
        batch_op.drop_column('name')

    # ### end Alembic commands ###
