"""empty message

Revision ID: 887a4d9110ae
Revises: 14a3924e1f3f
Create Date: 2021-02-25 22:38:29.554663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '887a4d9110ae'
down_revision = '14a3924e1f3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('call_in', schema=None) as batch_op:
        batch_op.add_column(sa.Column('destination', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('call_in', schema=None) as batch_op:
        batch_op.drop_column('destination')

    # ### end Alembic commands ###
