"""empty message

Revision ID: 9abd8f50e502
Revises: 2659becb4042
Create Date: 2020-10-29 16:20:08.432370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9abd8f50e502'
down_revision = '2659becb4042'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_constraint('person_client_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'client', ['client_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('person_client_id_fkey', 'employee', ['client_id'], ['id'])

    # ### end Alembic commands ###
