"""empty message

Revision ID: bfbc4b72cc00
Revises: c0c4eba3722b
Create Date: 2020-06-04 20:46:42.407947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfbc4b72cc00'
down_revision = 'c0c4eba3722b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_place', schema=None) as batch_op:
        batch_op.drop_index('ix_client_place_name_place')
        batch_op.create_index(batch_op.f('ix_client_place_name_place'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_place', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_place_name_place'))
        batch_op.create_index('ix_client_place_name_place', ['name'], unique=True)

    # ### end Alembic commands ###
