"""empty message

Revision ID: c0c4eba3722b
Revises: 2dd6c77dc2e4
Create Date: 2020-06-04 11:01:42.033823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0c4eba3722b'
down_revision = '2dd6c77dc2e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_place', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug_link', sa.String(length=128), nullable=True))
        batch_op.create_index(batch_op.f('ix_client_place_slug_link'), ['slug_link'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_place', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_place_slug_link'))
        batch_op.drop_column('slug_link')

    # ### end Alembic commands ###
