"""empty message

Revision ID: c7692d0835e5
Revises: 77e14829db2d
Create Date: 2020-06-15 00:54:27.973732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7692d0835e5'
down_revision = '77e14829db2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_place', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_client_place_name'), ['name'], unique=False)
        batch_op.drop_index('ix_client_place_name_place')
        batch_op.drop_column('name_place')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_place', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name_place', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
        batch_op.create_index('ix_client_place_name_place', ['name_place'], unique=False)
        batch_op.drop_index(batch_op.f('ix_client_place_name'))
        batch_op.drop_column('name')

    # ### end Alembic commands ###
