"""empty message

Revision ID: ca3e8588e1cd
Revises: 3fd7ead04af7
Create Date: 2020-11-05 23:54:20.286672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca3e8588e1cd'
down_revision = '3fd7ead04af7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee_to_group_client_places')
    op.drop_table('employee_to_client_place')
    with op.batch_alter_table('corporation', schema=None) as batch_op:
        batch_op.drop_constraint('corporation_creator_admin_id_fkey', type_='foreignkey')
        batch_op.drop_column('creator_admin_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('corporation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creator_admin_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('corporation_creator_admin_id_fkey', 'admin', ['creator_admin_id'], ['id'])

    op.create_table('employee_to_client_place',
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('client_place_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['client_place_id'], ['client_place.id'], name='employee_to_client_place_client_place_id_fkey'),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], name='employee_to_client_place_employee_id_fkey')
    )
    op.create_table('employee_to_group_client_places',
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('group_client_places_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], name='employee_to_group_client_places_employee_id_fkey'),
    sa.ForeignKeyConstraint(['group_client_places_id'], ['group_client_places.id'], name='employee_to_group_client_places_group_client_places_id_fkey')
    )
    # ### end Alembic commands ###
