"""empty message

Revision ID: d9f1df9be59c
Revises: 9abd8f50e502
Create Date: 2020-11-04 15:34:31.459050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9f1df9be59c'
down_revision = '9abd8f50e502'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_client_place',
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('client_place_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_place_id'], ['client_place.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], )
    )
    op.drop_table('user_client_place')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_client_place',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('client_place_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['client_place_id'], ['client_place.id'], name='user_client_place_client_place_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_client_place_user_id_fkey')
    )
    op.drop_table('employee_client_place')
    # ### end Alembic commands ###
