"""empty message

Revision ID: e0d15291d0a4
Revises: 5b3c2af53037
Create Date: 2021-01-24 15:31:57.337848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0d15291d0a4'
down_revision = '5b3c2af53037'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telegram_chat_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('use_email_for_call', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('use_telegram_for_call', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_employee_telegram_chat_id'), ['telegram_chat_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employee_telegram_chat_id'))
        batch_op.drop_column('use_telegram_for_call')
        batch_op.drop_column('use_email_for_call')
        batch_op.drop_column('telegram_chat_id')

    # ### end Alembic commands ###
