"""empty message

Revision ID: e7a4faa3d7b1
Revises: 7cfe7b8b494e
Create Date: 2020-11-06 23:48:07.297300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7a4faa3d7b1'
down_revision = '7cfe7b8b494e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('corporation', schema=None) as batch_op:
        batch_op.drop_constraint('corporation_creator_admin_id_fkey', type_='foreignkey')
        batch_op.drop_column('creator_admin_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('corporation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creator_admin_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('corporation_creator_admin_id_fkey', 'admin', ['creator_admin_id'], ['id'])

    # ### end Alembic commands ###
