"""empty message

Revision ID: ea07d5386d18
Revises: d9f1df9be59c
Create Date: 2020-11-04 16:01:52.299360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea07d5386d18'
down_revision = 'd9f1df9be59c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees_client_places',
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('client_place_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_place_id'], ['client_place.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], )
    )
    op.drop_table('employee_client_place')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_client_place',
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('client_place_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['client_place_id'], ['client_place.id'], name='employee_client_place_client_place_id_fkey'),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], name='employee_client_place_employee_id_fkey')
    )
    op.drop_table('employees_client_places')
    # ### end Alembic commands ###
